let ages = [3, 9, 23, 64, 2,8, 25, 93];
console.log(ages[ages.length-1]- ages[0]);

// Add a new age to your array and repeat the step above 
//to ensure it is dynamic (works for arrays of different lengths).

ages.push(5);
console.log(ages);
console.log(ages[ages.length-1]- ages[0]);


//Create an array called names that contains the following values: ‘Sam’, ‘Tommy’, ‘Tim’, ‘Sally’, ‘Buck’, ‘Bob’.
let names = ["Sam", "Tommy", "Tim", "Sally", "Buck", "Bob"];
console.log(names);

//Use a loop to iterate through the array and calculate the average number of letters per name. Print the result to the console.


//Use a loop to iterate through the array again and concatenate all the names together, separated by spaces, and print the result to the console.


// 3. How do you access the last element of an array?
// 4. How do you access the first element of an array?
// 5. Create a new array called nameLengths. Write a loop to iterate over the previously created names array and add the length of each name to the nameLengths array.
//For example:

//namesArray = ["Kelly", "Sam", "Kate"] //given this array
//nameLengths = [5, 3, 4] //create this new array

//6.



